### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by uramnoil**
## Description

I just fixed the typo.

### CODE REVIEW

**Comment by wzyyyyyyy** [comment]
@UramnOIL maybe you should not create pull request

**Comment by Jaciezyt** [comment]
i will fix it in crowdin. Thanks for contribution

**Comment by uramnoil** [comment]
Sorry for the pull request.
I'm new to crowdin and couldn't find the English file, where is it on crowdin?

**Comment by Jaciezyt** [comment]
> Sorry for the pull request. I'm new to crowdin and couldn't find the English file, where is it on crowdin?

Never mind.
you don't have permission to view source xD
btw, could u please tell me if you are in our discord server? i will add you to translator roles

**Comment by uramnoil** [comment]
This is my account: うらむんオイル#9594

**Pull request closed without merging**
