### PR TITLE
Move ParticleAPI to dll

### PR DESCRIPTION
**Pull request by OEOTYAN**
## Description

Please carefully read the [Contributing note](https://docs.litebds.com/#/zh_CN/Maintenance/README) before making any pull requests.
And, **Do not make a pull request to merge into main branch unless it is a hotfix. Use the beta branch instead.**
## Type of changes

- [x] Bug fix
- [x] New feature 
- [x] Enhancement
- [x] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://docs.litebds.com/#/zh_CN/Maintenance/README)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Review by Jaciezyt — COMMENTED** [review]
最好加一下Doxygen注释

**Comment by OEOTYAN** [comment]
草

**Review by dreamguxiang — APPROVED** [review]

**Comment by Jaciezyt** [comment]
> 草

没文档的话可能没人会用（（

**Comment by OEOTYAN** [comment]
哈哈 所有参数 默认参数都和脚本写的一样 甚至可以照抄脚本文档

**Comment by yqs112358** [comment]
先合了再说，尽快发2.6.0
现在其他部分doxygen一个没写呢，不要强求PR

**Comment by yqs112358** [comment]
没问题的话我合了？有人测试过功能正常工作嘛

**Pull request merged**
