### PR TITLE
Hey Russia!

### PR DESCRIPTION
**Pull request by mikhaillav**
## Description

So, i add a Russian language to docs, now i translated like 2% from all docs, but i will translate all docs.

### CODE REVIEW

**Comment by yqs112358** [comment]
Thanks for your contribution! It helps the community much 😀

**Comment by dreamguxiang** [comment]
finish？

**Comment by mikhaillav** [comment]
not yet

**Comment by yqs112358** [comment]
Hello~ If you are interested, welcome to join our LL developers telegram group
https://t.me/+pTDHsVifduEwZTM1
here to chat with developers more easily

**Comment by KawaiiNahida** [comment]
Documents were moved to new repo: https://github.com/LiteLDev/docs

**Pull request closed without merging**
