### PR TITLE
Add FormResponsePacketEvent

### PR DESCRIPTION
**Pull request by S3v3Nice**
## Description
Added FormResponsePacketEvent. This can be useful, for example, if you create your own api for form handling.

## Type of changes
- [ ] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/LiteLDev/LiteLoaderBDS/discussions/546)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Jaciezyt** [comment]
reslove conflicts plz

**Comment by S3v3Nice** [comment]
If I change onFormSelected to onFormResponsePacket in SE EventAPI, there will be a conflict again? :D

**Comment by Jaciezyt** [comment]
You should consider compatibility first
solving conflicts is very easy

**Comment by S3v3Nice** [comment]
I did it! It is compatible because onFormSelected was not implemented in SE, only in the enum class EVENT_TYPES

**Review by ShrBox — APPROVED** [review]

**Review by dreamguxiang — APPROVED** [review]

**Pull request merged**
