### PR TITLE
Finalize InventoryTransaction member variable implementation

### PR DESCRIPTION
**Pull request by StrafeIQ**
Finalize Transaction member variable implementation

### CODE REVIEW

**Comment by OEOTYAN** [comment]
All mc class member names should begin with m.

**Comment by StrafeIQ** [comment]
> All mc class member names should begin with m.

ok

**Comment by StrafeIQ** [comment]
Are you going to change it or should I do that?

**Comment by OEOTYAN** [comment]
> Are you going to change it or should I do that?

I'm working on client support and don't have time right now, so help yourself.

**Comment by StrafeIQ** [comment]
> > Are you going to change it or should I do that?
> 
> I'm working on client support and don't have time right now, so help yourself.

I've taken care of it now

**Review by OEOTYAN — APPROVED** [review]

**Pull request merged**
