### PR TITLE
Add `PlayerInteractEntityEvent`

### PR DESCRIPTION
**Pull request by S3v3Nice**
## Type of changes
- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/LiteLDev/LiteLoaderBDS/discussions/546)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by dreamguxiang** [comment]
ItemUseOnActorEvent is required to exist if the player intersects with an entity that exists only on the client. This usually exists when the server sends a entity packet to the client (for NPC plugins)

**Comment by S3v3Nice** [comment]
> if the player intersects with an entity

What do you mean by 'intersects'? I checked, the event is triggered only when the player *interacts* with the entity with the right or left mouse button. 

`mInteractiveMode` didn't clearly indicate whether the button was left or right, so I decided to add an enum. Plus it wasn't clear which player did it, so I added the `mPlayer` field. Plus there was a field with a `RuntimeId` of actor, but it wasn't convenient, so I made the field with `Actor` object. So it turns out that it' s better to create a separate event (PlayerInteractEntityEvent) for compatibility.

What's the problem with using the new event instead of the old one? I'm not suggesting you delete the old one right away, let it be marked as `deprecated` or you can just leave it (although I do not understand who use this event, if there is not even a field `mPlayer`).

**Comment by dreamguxiang** [comment]
> > if the player intersects with an entity
> 
> What do you mean by 'intersects'? I checked, the event is triggered only when the player _interacts_ with the entity with the right or left mouse button.
> 
> `mInteractiveMode` didn't clearly indicate whether the button was left or right, so I decided to add an enum. Plus it wasn't clear which player did it, so I added the `mPlayer` field. Plus there was a field with a `RuntimeId` of actor, but it wasn't convenient, so I made the field with `Actor` object. So it turns out that it' s better to create a separate event (PlayerInteractEntityEvent) for compatibility.
> 
> What's the problem with using the new event instead of the old one? I'm not suggesting you delete the old one right away, let it be marked as `deprecated` or you can just leave it (although I do not understand who use this event, if there is not even a field `mPlayer`).

If the entity does not exist in the server, it will not own the actor object, Only the runtimeid can be used to determine it.

try ` Player::AddEntityPacket `

ItemUseOnActorEvent you can also change to a better name instead of deprecating

**Comment by S3v3Nice** [comment]
Okay, what about this?

**Pull request merged**
