### PR TITLE
Add More Dimension API

### PR DESCRIPTION
**Pull request by quizhizhe**
## What does this PR do?

Add More Dimension API

## Which issues does this PR resolve?

Null

## Checklist before merging

Thank you for your contribution to the repository. 
Before submitting this PR, please make sure:

- [x] Your code builds clean without any errors or warnings
- [x] Your code follows the code style of this repository (see the wiki)
- [x] You have tested all functions
- [x] You have not used code without license
- [x] You have added statement for third-party code

### CODE REVIEW

**Comment by MCBEPluginModer** [comment]
This is full Dimension API and support custom world generator?

**Comment by quizhizhe** [comment]
> This is full Dimension API and support custom world generator?

Not complete

**Comment by MCBEPluginModer** [comment]
> > This is full Dimension API and support custom world generator?
> 
> Not complete

How to use updated API and when will the full API be fully added?

**Comment by banchen19** [comment]
cool ！then can use custom dimensions later.

**Pull request merged**
