### PR TITLE
Add LiteLoader.NET Pre-loader support

### PR DESCRIPTION
**Pull request by Yushu2606**
## Description

Please carefully read the [Contributing note](https://docs.litebds.com/#/zh_CN/Maintenance/README) before making any pull requests.
And, **Do not make a pull request to merge into main branch unless it is a hotfix. Use the beta branch instead.**
## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://docs.litebds.com/#/zh_CN/Maintenance/README)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Redbeanw44602** [comment]
这个路径看起来不太好

**Review by Jaciezyt — APPROVED** [review]

**Comment by RimuruChan** [comment]
这是什么作用

**Comment by Yushu2606** [comment]
> 这是什么作用

LLNETPreLoader是拿来加载独立.NET Runtime的

**Comment by Yushu2606** [comment]
> 这个路径看起来不太好

那么？

**Comment by Jaciezyt** [comment]
Close?

**Comment by Yushu2606** [comment]
idk

**Pull request closed without merging**
